import type { Metadata } from "next";
import "./global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-us">
      <body>
        <header>
          <h1>Wowaudit Raid Group Maker</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
