import { ClassSpec, stringToClassSpec } from "@wowaudit-tools/utils/classSpec";

// TODO: should stub less here, but need to figure out secret storage before working with WCL API

const ENCOUNTER_TO_ID: { [key: string]: number } = {
  Gnarlroot: 2820,
  "Igira the Cruel": 2709,
  Volcoross: 2737,
  "Council of Dreams": 2728,
  Larodar: 2731,
  Nymue: 2708,
  Smolderon: 2824,
  "Tindral Sageswift": 2786,
  Fyrakk: 2677
};

const MOCK_ENCOUNTER_SPEC_PRIO: { [key: number]: string[] } = {
  2820: [
    "Demonology Warlock",
    "Marksmanship Hunter",
    "Subtlety Rogue",
    "Arcane Mage",
    "Outlaw Rogue",
    "Assassination Rogue",
    "Beast Mastery Hunter",
    "Havoc Demon Hunter",
    "Affliction Warlock",
    "Windwalker Monk",
    "Fire Mage",
    "Devastation Evoker",
    "Fury Warrior",
    "Feral Druid",
    "Enhancement Shaman",
    "Frost Death Knight",
    "Frost Mage",
    "Balance Druid",
    "Shadow Priest",
    "Retribution Paladin",
    "Augmentation Evoker",
    "Destruction Warlock",
    "Unholy Death Knight",
    "Survival Hunter",
    "Elemental Shaman",
    "Arms Warrior"
  ],
  2709: [
    "Fury Warrior",
    "Outlaw Rogue",
    "Arcane Mage",
    "Fire Mage",
    "Subtlety Rogue",
    "Demonology Warlock",
    "Assassination Rogue",
    "Havoc Demon Hunter",
    "Windwalker Monk",
    "Affliction Warlock",
    "Enhancement Shaman",
    "Shadow Priest",
    "Devastation Evoker",
    "Beast Mastery Hunter",
    "Destruction Warlock",
    "Unholy Death Knight",
    "Frost Mage",
    "Retribution Paladin",
    "Marksmanship Hunter",
    "Elemental Shaman",
    "Frost Death Knight",
    "Survival Hunter",
    "Arms Warrior",
    "Feral Druid",
    "Balance Druid",
    "Augmentation Evoker"
  ],
  2737: [
    "Subtlety Rogue",
    "Enhancement Shaman",
    "Unholy Death Knight",
    "Fury Warrior",
    "Frost Death Knight",
    "Outlaw Rogue",
    "Arcane Mage",
    "Arms Warrior",
    "Balance Druid",
    "Retribution Paladin",
    "Feral Druid",
    "Windwalker Monk",
    "Survival Hunter",
    "Havoc Demon Hunter",
    "Beast Mastery Hunter",
    "Assassination Rogue",
    "Fire Mage",
    "Devastation Evoker",
    "Destruction Warlock",
    "Demonology Warlock",
    "Elemental Shaman",
    "Affliction Warlock",
    "Frost Mage",
    "Shadow Priest",
    "Marksmanship Hunter",
    "Augmentation Evoker"
  ],
  2728: [
    "Balance Druid",
    "Elemental Shaman",
    "Shadow Priest",
    "Destruction Warlock",
    "Enhancement Shaman",
    "Affliction Warlock",
    "Havoc Demon Hunter",
    "Arms Warrior",
    "Marksmanship Hunter",
    "Fire Mage",
    "Frost Mage",
    "Devastation Evoker",
    "Assassination Rogue",
    "Windwalker Monk",
    "Survival Hunter",
    "Demonology Warlock",
    "Outlaw Rogue",
    "Fury Warrior",
    "Arcane Mage",
    "Feral Druid",
    "Subtlety Rogue",
    "Beast Mastery Hunter",
    "Frost Death Knight",
    "Retribution Paladin",
    "Unholy Death Knight",
    "Augmentation Evoker"
  ],
  2731: [
    "Marksmanship Hunter",
    "Enhancement Shaman",
    "Arcane Mage",
    "Demonology Warlock",
    "Havoc Demon Hunter",
    "Fury Warrior",
    "Frost Mage",
    "Outlaw Rogue",
    "Destruction Warlock",
    "Windwalker Monk",
    "Elemental Shaman",
    "Affliction Warlock",
    "Fire Mage",
    "Beast Mastery Hunter",
    "Survival Hunter",
    "Devastation Evoker",
    "Subtlety Rogue",
    "Shadow Priest",
    "Retribution Paladin",
    "Arms Warrior",
    "Unholy Death Knight",
    "Assassination Rogue",
    "Frost Death Knight",
    "Balance Druid",
    "Feral Druid",
    "Augmentation Evoker"
  ],
  2708: [
    "Windwalker Monk",
    "Beast Mastery Hunter",
    "Enhancement Shaman",
    "Subtlety Rogue",
    "Assassination Rogue",
    "Destruction Warlock",
    "Fury Warrior",
    "Survival Hunter",
    "Marksmanship Hunter",
    "Demonology Warlock",
    "Retribution Paladin",
    "Feral Druid",
    "Outlaw Rogue",
    "Devastation Evoker",
    "Havoc Demon Hunter",
    "Affliction Warlock",
    "Arcane Mage",
    "Elemental Shaman",
    "Fire Mage",
    "Frost Mage",
    "Arms Warrior",
    "Balance Druid",
    "Unholy Death Knight",
    "Shadow Priest",
    "Frost Death Knight",
    "Augmentation Evoker"
  ],
  2824: [
    "Subtlety Rogue",
    "Beast Mastery Hunter",
    "Survival Hunter",
    "Unholy Death Knight",
    "Arcane Mage",
    "Assassination Rogue",
    "Fury Warrior",
    "Demonology Warlock",
    "Outlaw Rogue",
    "Enhancement Shaman",
    "Elemental Shaman",
    "Marksmanship Hunter",
    "Retribution Paladin",
    "Arms Warrior",
    "Fire Mage",
    "Destruction Warlock",
    "Havoc Demon Hunter",
    "Affliction Warlock",
    "Windwalker Monk",
    "Balance Druid",
    "Feral Druid",
    "Devastation Evoker",
    "Frost Mage",
    "Shadow Priest",
    "Frost Death Knight",
    "Augmentation Evoker"
  ],
  2786: [
    "Demonology Warlock",
    "Devastation Evoker",
    "Affliction Warlock",
    "Havoc Demon Hunter",
    "Frost Mage",
    "Outlaw Rogue",
    "Beast Mastery Hunter",
    "Subtlety Rogue",
    "Arcane Mage",
    "Assassination Rogue",
    "Fire Mage",
    "Windwalker Monk",
    "Augmentation Evoker",
    "Frost Death Knight",
    "Fury Warrior",
    "Unholy Death Knight",
    "Balance Druid",
    "Retribution Paladin",
    "Shadow Priest",
    "Elemental Shaman",
    "Enhancement Shaman",
    "Feral Druid"
  ],
  2677: [
    "Windwalker Monk",
    "Havoc Demon Hunter",
    "Outlaw Rogue",
    "Fury Warrior",
    "Enhancement Shaman",
    "Demonology Warlock",
    "Subtlety Rogue",
    "Shadow Priest",
    "Assassination Rogue",
    "Beast Mastery Hunter",
    "Elemental Shaman",
    "Arcane Mage",
    "Fire Mage",
    "Frost Death Knight",
    "Retribution Paladin",
    "Unholy Death Knight",
    "Balance Druid",
    "Augmentation Evoker",
    "Feral Druid",
    "Frost Mage"
  ]
};

export async function getSpecPriorityForEncounter(
  encounterName: string
): Promise<ClassSpec[]> {
  return MOCK_ENCOUNTER_SPEC_PRIO[ENCOUNTER_TO_ID[encounterName]].map(
    stringToClassSpec
  );
}
